apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Custom Nginx Page</title>
    </head>
    <body>
        <h1>Hello from ConfigMap!</h1>
        <p>This HTML is served from a Kubernetes ConfigMap</p>
    </body>
    </html>